select distinct brand from car;

create database db_act1;
use db_act1;

create table car (
	id INT,
	model VARCHAR(50),
	brand VARCHAR(50),
	year VARCHAR(50)
);
insert into car (id, model, brand, year) values (1, 'Passat', 'Volkswagen', 1990);
insert into car (id, model, brand, year) values (2, 'Tracker', 'Chevrolet', 1999);
insert into car (id, model, brand, year) values (3, '300SE', 'Mercedes-Benz', 1993);
insert into car (id, model, brand, year) values (4, 'Outback', 'Subaru', 2005);
insert into car (id, model, brand, year) values (5, 'Excel', 'Mitsubishi', 1988);
insert into car (id, model, brand, year) values (6, 'Ram Wagon B350', 'Dodge', 1994);
insert into car (id, model, brand, year) values (7, 'Estate', 'Buick', 1990);
insert into car (id, model, brand, year) values (8, 'NSX', 'Acura', 1997);
insert into car (id, model, brand, year) values (9, 'Prelude', 'Honda', 1999);
insert into car (id, model, brand, year) values (10, 'Verona', 'Suzuki', 2005);
insert into car (id, model, brand, year) values (11, 'GT350', 'Shelby', 1969);
insert into car (id, model, brand, year) values (12, 'H1', 'Hummer', 1994);
insert into car (id, model, brand, year) values (13, 'Maxima', 'Nissan', 2002);
insert into car (id, model, brand, year) values (14, '900', 'Saab', 1990);
insert into car (id, model, brand, year) values (15, 'xB', 'Scion', 2011);
insert into car (id, model, brand, year) values (16, 'Viper', 'Dodge', 2000);
insert into car (id, model, brand, year) values (17, 'Lancer Evolution', 'Mitsubishi', 2010);
insert into car (id, model, brand, year) values (18, 'X3', 'BMW', 2011);
insert into car (id, model, brand, year) values (19, 'Brooklands', 'Bentley', 2009);
insert into car (id, model, brand, year) values (20, 'Prius', 'Toyota', 2010);
insert into car (id, model, brand, year) values (21, 'F-Series', 'Ford', 1991);
insert into car (id, model, brand, year) values (22, 'Sephia', 'Kia', 2001);
insert into car (id, model, brand, year) values (23, 'GTO', 'Pontiac', 2005);
insert into car (id, model, brand, year) values (24, 'Monterey', 'Pontiac', 2005);
insert into car (id, model, brand, year) values (25, 'Sundance', 'Plymouth', 1993);
insert into car (id, model, brand, year) values (26, 'Navajo', 'Mazda', 1991);
insert into car (id, model, brand, year) values (27, 'C-Class', 'Mercedes-Benz', 1993);
insert into car (id, model, brand, year) values (28, 'Avenger', 'Dodge', 1995);
insert into car (id, model, brand, year) values (29, 'Grand Prix Turbo', 'Pontiac', 1990);
insert into car (id, model, brand, year) values (30, 'Titan', 'Nissan', 2007);
insert into car (id, model, brand, year) values (31, 'Astro', 'Chevrolet', 1993);
insert into car (id, model, brand, year) values (32, 'Monte Carlo', 'Chevrolet', 1998);
insert into car (id, model, brand, year) values (33, '626', 'Mazda', 1989);
insert into car (id, model, brand, year) values (34, 'Grand Vitara', 'Suzuki', 2002);
insert into car (id, model, brand, year) values (35, 'Outlander', 'Mitsubishi', 2004);
insert into car (id, model, brand, year) values (36, 'Ion', 'Saturn', 2003);
insert into car (id, model, brand, year) values (37, 'Entourage', 'Hyundai', 2009);
insert into car (id, model, brand, year) values (38, 'Grand Cherokee', 'Jeep', 2000);
insert into car (id, model, brand, year) values (39, 'TT', 'Audi', 2004);
insert into car (id, model, brand, year) values (40, 'Sierra 1500', 'GMC', 2002);
insert into car (id, model, brand, year) values (41, 'B-Series', 'Mazda', 1994);
insert into car (id, model, brand, year) values (42, 'Cougar', 'Mercury', 1990);
insert into car (id, model, brand, year) values (43, 'Exige', 'Lotus', 2011);
insert into car (id, model, brand, year) values (44, 'GLK-Class', 'Mercedes-Benz', 2010);
insert into car (id, model, brand, year) values (45, 'Excursion', 'Ford', 2005);
insert into car (id, model, brand, year) values (46, 'ES', 'Lexus', 1991);
insert into car (id, model, brand, year) values (47, 'Impala', 'Chevrolet', 2004);
insert into car (id, model, brand, year) values (48, 'Savana', 'GMC', 2009);
insert into car (id, model, brand, year) values (49, 'Mighty Max Macro', 'Mitsubishi', 1993);
insert into car (id, model, brand, year) values (50, 'A3', 'Audi', 2008);
insert into car (id, model, brand, year) values (51, 'Camry Solara', 'Toyota', 2006);
insert into car (id, model, brand, year) values (52, 'GT-R', 'Nissan', 2010);
insert into car (id, model, brand, year) values (53, 'Acadia', 'GMC', 2007);
insert into car (id, model, brand, year) values (54, 'Chariot', 'Mitsubishi', 1986);
insert into car (id, model, brand, year) values (55, 'Camry', 'Toyota', 1996);
insert into car (id, model, brand, year) values (56, 'Elantra', 'Hyundai', 2010);
insert into car (id, model, brand, year) values (57, 'Impala', 'Chevrolet', 2007);
insert into car (id, model, brand, year) values (58, 'C/V', 'Ram', 2012);
insert into car (id, model, brand, year) values (59, 'C70', 'Volvo', 1998);
insert into car (id, model, brand, year) values (60, '200', 'Chrysler', 2012);
insert into car (id, model, brand, year) values (61, 'XC60', 'Volvo', 2012);
insert into car (id, model, brand, year) values (62, 'Altima', 'Nissan', 2003);
insert into car (id, model, brand, year) values (63, 'Tundra', 'Toyota', 2002);
insert into car (id, model, brand, year) values (64, 'Mirage', 'Mitsubishi', 1988);
insert into car (id, model, brand, year) values (65, 'Dakota Club', 'Dodge', 1992);
insert into car (id, model, brand, year) values (66, 'Eos', 'Volkswagen', 2009);
insert into car (id, model, brand, year) values (67, 'Aveo', 'Chevrolet', 2011);
insert into car (id, model, brand, year) values (68, 'G-Class', 'Mercedes-Benz', 2002);
insert into car (id, model, brand, year) values (69, 'Prizm', 'Geo', 1997);
insert into car (id, model, brand, year) values (70, 'V8 Vantage', 'Aston Martin', 2008);
insert into car (id, model, brand, year) values (71, 'Tracer', 'Mercury', 1989);
insert into car (id, model, brand, year) values (72, '960', 'Volvo', 1997);
insert into car (id, model, brand, year) values (73, 'Mustang', 'Ford', 1986);
insert into car (id, model, brand, year) values (74, 'Savana 1500', 'GMC', 2009);
insert into car (id, model, brand, year) values (75, 'Integra', 'Acura', 1994);
insert into car (id, model, brand, year) values (76, 'S10', 'Chevrolet', 1999);
insert into car (id, model, brand, year) values (77, 'MX-6', 'Mazda', 1992);
insert into car (id, model, brand, year) values (78, 'Town Car', 'Lincoln', 2006);
insert into car (id, model, brand, year) values (79, 'Compass', 'Jeep', 2009);
insert into car (id, model, brand, year) values (80, 'Elantra', 'Hyundai', 1997);
insert into car (id, model, brand, year) values (81, 'Veloster', 'Hyundai', 2013);
insert into car (id, model, brand, year) values (82, 'Express 1500', 'Chevrolet', 2009);
insert into car (id, model, brand, year) values (83, 'Maxima', 'Nissan', 2007);
insert into car (id, model, brand, year) values (84, 'GTO', 'Mitsubishi', 1990);
insert into car (id, model, brand, year) values (85, 'Accord Crosstour', 'Honda', 2010);
insert into car (id, model, brand, year) values (86, 'Savana 2500', 'GMC', 2002);
insert into car (id, model, brand, year) values (87, 'Civic', 'Honda', 2007);
insert into car (id, model, brand, year) values (88, 'Pajero', 'Mitsubishi', 1996);
insert into car (id, model, brand, year) values (89, 'GTI', 'Volkswagen', 2009);
insert into car (id, model, brand, year) values (90, 'Thunderbird', 'Ford', 2002);
insert into car (id, model, brand, year) values (91, 'Raider', 'Mitsubishi', 2007);
insert into car (id, model, brand, year) values (92, 'Odyssey', 'Honda', 2008);
insert into car (id, model, brand, year) values (93, 'Sedona', 'Kia', 2005);
insert into car (id, model, brand, year) values (94, 'Camry', 'Toyota', 1995);
insert into car (id, model, brand, year) values (95, 'TT', 'Audi', 2010);
insert into car (id, model, brand, year) values (96, 'Sierra 2500', 'GMC', 2012);
insert into car (id, model, brand, year) values (97, 'Shadow', 'Dodge', 1994);
insert into car (id, model, brand, year) values (98, 'LS', 'Lexus', 2008);
insert into car (id, model, brand, year) values (99, 'X5', 'BMW', 2009);
insert into car (id, model, brand, year) values (100, 'Ciera', 'Oldsmobile', 1995);
insert into car (id, model, brand, year) values (101, 'Avalon', 'Toyota', 2000);
insert into car (id, model, brand, year) values (102, 'Imperial', 'Chrysler', 1926);
insert into car (id, model, brand, year) values (103, 'Ranger', 'Ford', 1998);
insert into car (id, model, brand, year) values (104, 'Spirit', 'Dodge', 1993);
insert into car (id, model, brand, year) values (105, 'Express 1500', 'Chevrolet', 1997);
insert into car (id, model, brand, year) values (106, 'GS', 'Lexus', 2000);
insert into car (id, model, brand, year) values (107, 'Roadmaster', 'Buick', 1996);
insert into car (id, model, brand, year) values (108, 'Skylark', 'Buick', 1985);
insert into car (id, model, brand, year) values (109, 'DB9', 'Aston Martin', 2006);
insert into car (id, model, brand, year) values (110, 'Sunbird', 'Pontiac', 1987);
insert into car (id, model, brand, year) values (111, 'Th!nk', 'Ford', 2000);
insert into car (id, model, brand, year) values (112, 'SL-Class', 'Mercedes-Benz', 1993);
insert into car (id, model, brand, year) values (113, 'RX-7', 'Mazda', 1987);
insert into car (id, model, brand, year) values (114, 'Mazda3', 'Mazda', 2010);
insert into car (id, model, brand, year) values (115, 'Rodeo', 'Isuzu', 2004);
insert into car (id, model, brand, year) values (116, 'Yukon', 'GMC', 2001);
insert into car (id, model, brand, year) values (117, 'GTI', 'Volkswagen', 2011);
insert into car (id, model, brand, year) values (118, 'A8', 'Audi', 2005);
insert into car (id, model, brand, year) values (119, 'M5', 'BMW', 2002);
insert into car (id, model, brand, year) values (120, 'Z4 M', 'BMW', 2008);
insert into car (id, model, brand, year) values (121, 'RX-7', 'Mazda', 1989);
insert into car (id, model, brand, year) values (122, 'J', 'Infiniti', 1994);
insert into car (id, model, brand, year) values (123, 'Express 1500', 'Chevrolet', 2000);
insert into car (id, model, brand, year) values (124, 'X6', 'BMW', 2009);
insert into car (id, model, brand, year) values (125, 'E250', 'Ford', 2009);
insert into car (id, model, brand, year) values (126, 'H2', 'Hummer', 2009);
insert into car (id, model, brand, year) values (127, 'Colt', 'Dodge', 1994);
insert into car (id, model, brand, year) values (128, 'Voyager', 'Chrysler', 2003);
insert into car (id, model, brand, year) values (129, 'Venture', 'Chevrolet', 1997);
insert into car (id, model, brand, year) values (130, 'Mustang', 'Ford', 2007);
insert into car (id, model, brand, year) values (131, 'Skyhawk', 'Buick', 1984);
insert into car (id, model, brand, year) values (132, 'LS', 'Lexus', 2000);
insert into car (id, model, brand, year) values (133, 'Corsica', 'Chevrolet', 1996);
insert into car (id, model, brand, year) values (134, 'Premier', 'Eagle', 1992);
insert into car (id, model, brand, year) values (135, 'Trooper', 'Isuzu', 1992);
insert into car (id, model, brand, year) values (136, 'Forenza', 'Suzuki', 2008);
insert into car (id, model, brand, year) values (137, '928', 'Porsche', 1985);
insert into car (id, model, brand, year) values (138, 'Corolla', 'Toyota', 2001);
insert into car (id, model, brand, year) values (139, 'Defender', 'Land Rover', 1993);
insert into car (id, model, brand, year) values (140, 'Challenger', 'Mitsubishi', 2003);
insert into car (id, model, brand, year) values (141, 'Seville', 'Cadillac', 2001);
insert into car (id, model, brand, year) values (142, 'Maxima', 'Nissan', 2007);
insert into car (id, model, brand, year) values (143, 'ES', 'Lexus', 2006);
insert into car (id, model, brand, year) values (144, 'V40', 'Volvo', 2000);
insert into car (id, model, brand, year) values (145, 'Grand Caravan', 'Dodge', 2000);
insert into car (id, model, brand, year) values (146, 'Passport', 'Honda', 1995);
insert into car (id, model, brand, year) values (147, 'Pajero', 'Mitsubishi', 1993);
insert into car (id, model, brand, year) values (148, 'NSX', 'Acura', 1996);
insert into car (id, model, brand, year) values (149, 'LeSabre', 'Buick', 1986);
insert into car (id, model, brand, year) values (150, 'DB9', 'Aston Martin', 2009);
insert into car (id, model, brand, year) values (151, 'CC', 'Volkswagen', 2013);
insert into car (id, model, brand, year) values (152, 'Ram Van 1500', 'Dodge', 2003);
insert into car (id, model, brand, year) values (153, 'Maxima', 'Nissan', 2011);
insert into car (id, model, brand, year) values (154, 'Arnage', 'Bentley', 2006);
insert into car (id, model, brand, year) values (155, 'Aspen', 'Chrysler', 2007);
insert into car (id, model, brand, year) values (156, 'tC', 'Scion', 2009);
insert into car (id, model, brand, year) values (157, 'Savana', 'GMC', 2007);
insert into car (id, model, brand, year) values (158, 'Daewoo Lacetti', 'Suzuki', 2005);
insert into car (id, model, brand, year) values (159, 'VUE', 'Saturn', 2005);
insert into car (id, model, brand, year) values (160, 'M5', 'BMW', 2009);
insert into car (id, model, brand, year) values (161, 'LX', 'Lexus', 2008);
insert into car (id, model, brand, year) values (162, 'Type 2', 'Volkswagen', 1987);
insert into car (id, model, brand, year) values (163, 'Compass', 'Jeep', 2011);
insert into car (id, model, brand, year) values (164, 'Previa', 'Toyota', 1997);
insert into car (id, model, brand, year) values (165, 'CL-Class', 'Mercedes-Benz', 1998);
insert into car (id, model, brand, year) values (166, '525', 'BMW', 2004);
insert into car (id, model, brand, year) values (167, 'Yukon XL 1500', 'GMC', 2008);
insert into car (id, model, brand, year) values (168, 'RX-7', 'Mazda', 1992);
insert into car (id, model, brand, year) values (169, 'Topaz', 'Mercury', 1986);
insert into car (id, model, brand, year) values (170, 'Thunderbird', 'Ford', 1986);
insert into car (id, model, brand, year) values (171, 'E-Class', 'Mercedes-Benz', 1998);
insert into car (id, model, brand, year) values (172, 'Mark LT', 'Lincoln', 2007);
insert into car (id, model, brand, year) values (173, 'A6', 'Audi', 2003);
insert into car (id, model, brand, year) values (174, 'E-Class', 'Mercedes-Benz', 2004);
insert into car (id, model, brand, year) values (175, 'XC90', 'Volvo', 2011);
insert into car (id, model, brand, year) values (176, 'ES', 'Lexus', 1998);
insert into car (id, model, brand, year) values (177, 'GranTurismo', 'Maserati', 2010);
insert into car (id, model, brand, year) values (178, 'Bronco', 'Ford', 1992);
insert into car (id, model, brand, year) values (179, 'Truck', 'Mitsubishi', 1996);
insert into car (id, model, brand, year) values (180, 'Borrego', 'Kia', 2009);
insert into car (id, model, brand, year) values (181, 'GS', 'Lexus', 1999);
insert into car (id, model, brand, year) values (182, 'RX-7', 'Mazda', 1993);
insert into car (id, model, brand, year) values (183, 'ES', 'Lexus', 2000);
insert into car (id, model, brand, year) values (184, 'Tahoe', 'Chevrolet', 2002);
insert into car (id, model, brand, year) values (185, 'Sunfire', 'Pontiac', 1999);
insert into car (id, model, brand, year) values (186, 'G-Series G30', 'Chevrolet', 1994);
insert into car (id, model, brand, year) values (187, 'Ram 1500', 'Dodge', 2009);
insert into car (id, model, brand, year) values (188, 'RAV4', 'Toyota', 2001);
insert into car (id, model, brand, year) values (189, 'Thunderbird', 'Ford', 2006);
insert into car (id, model, brand, year) values (190, 'Previa', 'Toyota', 1994);
insert into car (id, model, brand, year) values (191, '911', 'Porsche', 1988);
insert into car (id, model, brand, year) values (192, 'Yukon XL 2500', 'GMC', 2002);
insert into car (id, model, brand, year) values (193, 'Liberty', 'Jeep', 2009);
insert into car (id, model, brand, year) values (194, '6 Series', 'BMW', 2012);
insert into car (id, model, brand, year) values (195, '3 Series', 'BMW', 2011);
insert into car (id, model, brand, year) values (196, 'Equinox', 'Chevrolet', 2011);
insert into car (id, model, brand, year) values (197, 'TT', 'Audi', 2008);
insert into car (id, model, brand, year) values (198, 'S-Class', 'Mercedes-Benz', 2001);
insert into car (id, model, brand, year) values (199, 'Hombre Space', 'Isuzu', 1998);
insert into car (id, model, brand, year) values (200, 'Trans Sport', 'Pontiac', 1994);
insert into car (id, model, brand, year) values (201, 'Suburban 2500', 'GMC', 1993);
insert into car (id, model, brand, year) values (202, 'Z3', 'BMW', 1997);
insert into car (id, model, brand, year) values (203, 'Montero', 'Mitsubishi', 2001);
insert into car (id, model, brand, year) values (204, 'Routan', 'Volkswagen', 2011);
insert into car (id, model, brand, year) values (205, 'Quest', 'Nissan', 1998);
insert into car (id, model, brand, year) values (206, 'Sebring', 'Chrysler', 2009);
insert into car (id, model, brand, year) values (207, 'Pathfinder Armada', 'Nissan', 2004);
insert into car (id, model, brand, year) values (208, 'Prius c', 'Toyota', 2012);
insert into car (id, model, brand, year) values (209, 'Tracer', 'Mercury', 1995);
insert into car (id, model, brand, year) values (210, 'W201', 'Mercedes-Benz', 1987);
insert into car (id, model, brand, year) values (211, 'Montana', 'Pontiac', 2005);
insert into car (id, model, brand, year) values (212, 'TL', 'Acura', 2002);
insert into car (id, model, brand, year) values (213, 'Bronco', 'Ford', 1994);
insert into car (id, model, brand, year) values (214, 'F350', 'Ford', 1994);
insert into car (id, model, brand, year) values (215, 'B-Series Plus', 'Mazda', 2001);
insert into car (id, model, brand, year) values (216, 'Malibu', 'Chevrolet', 2007);
insert into car (id, model, brand, year) values (217, 'Corrado', 'Volkswagen', 1991);
insert into car (id, model, brand, year) values (218, 'Z4 M', 'BMW', 2007);
insert into car (id, model, brand, year) values (219, 'Century', 'Buick', 1987);
insert into car (id, model, brand, year) values (220, 'RAV4', 'Toyota', 2011);
insert into car (id, model, brand, year) values (221, 'Highlander', 'Toyota', 2005);
insert into car (id, model, brand, year) values (222, 'Suburban 2500', 'GMC', 1999);
insert into car (id, model, brand, year) values (223, 'Spyder', 'Maserati', 2005);
insert into car (id, model, brand, year) values (224, 'V70', 'Volvo', 2008);
insert into car (id, model, brand, year) values (225, 'Swift', 'Suzuki', 2000);
insert into car (id, model, brand, year) values (226, 'Oasis', 'Isuzu', 1996);
insert into car (id, model, brand, year) values (227, 'T100', 'Toyota', 1994);
insert into car (id, model, brand, year) values (228, 'Bravada', 'Oldsmobile', 2000);
insert into car (id, model, brand, year) values (229, 'Discovery', 'Land Rover', 2007);
insert into car (id, model, brand, year) values (230, '944', 'Porsche', 1985);
insert into car (id, model, brand, year) values (231, 'F150', 'Ford', 2005);
insert into car (id, model, brand, year) values (232, 'Expedition', 'Ford', 2007);
insert into car (id, model, brand, year) values (233, 'Forenza', 'Suzuki', 2008);
insert into car (id, model, brand, year) values (234, 'Continental Mark VII', 'Lincoln', 1992);
insert into car (id, model, brand, year) values (235, 'C8 Laviolette', 'Spyker', 2004);
insert into car (id, model, brand, year) values (236, 'Passat', 'Volkswagen', 1996);
insert into car (id, model, brand, year) values (237, 'Sonata', 'Hyundai', 2007);
insert into car (id, model, brand, year) values (238, 'Scirocco', 'Volkswagen', 1986);
insert into car (id, model, brand, year) values (239, 'Silverado 3500', 'Chevrolet', 2008);
insert into car (id, model, brand, year) values (240, 'Freelander', 'Land Rover', 2011);
insert into car (id, model, brand, year) values (241, 'Coachbuilder', 'Buick', 1994);
insert into car (id, model, brand, year) values (242, 'Tucson', 'Hyundai', 2011);
insert into car (id, model, brand, year) values (243, 'X3', 'BMW', 2008);
insert into car (id, model, brand, year) values (244, 'Fiesta', 'Ford', 2013);
insert into car (id, model, brand, year) values (245, 'Tahoe', 'Chevrolet', 1995);
insert into car (id, model, brand, year) values (246, 'MKS', 'Lincoln', 2009);
insert into car (id, model, brand, year) values (247, 'Expedition', 'Ford', 2004);
insert into car (id, model, brand, year) values (248, 'Pajero', 'Mitsubishi', 1990);
insert into car (id, model, brand, year) values (249, 'Z3', 'BMW', 1997);
insert into car (id, model, brand, year) values (250, 'Intrepid', 'Dodge', 2002);
